delivery/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

main/urls.py
from django.conf.urls import url

from . import views



urlpatterns =[
    url(r'weekly_menu/', views.WeeklyMenuListView.as_view(), name='weekly_menu'),
    url(r'^$', views.HomeListView.as_view(), name='home'),
    url(r'registration/', views.RegistrationFormView.as_view(), name='registration'),
    url(r'login/', views.LoginFormView.as_view(), name='login'),
    url(r'logout/', views.LogoutView.as_view(), name='logout'),
    url(r'change_password/', views.ChangePasswordFormView.as_view(), name='change_password'),
    url(r'change_items/', views.BasketChangeQuantityView.as_view(), name='basket_change'),
    url(r'address/', views.AddressTemplateView.as_view(), name='address'),
    url(r'time/', views.TimeDeliveryView.as_view(), name='time'),
    url(r'order/(?P<order_id>\d+)/$', views.OrderDetailView.as_view(), name='order_detail'),
    url(r'profile/', views.ProfileView.as_view(), name='profile'),
    url(r'get_route/', views.GetCurrentCourierView.as_view(), name = 'get_point'),

]

main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Client (models.Model):
    phone = models.CharField(max_length=20, unique=True)
    user = models.OneToOneField(User)


class Code (models.Model):

    code = models.CharField(max_length=6)
    phone = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)

main/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms

from main.service import CheckPhone
from main.models import Code


class RegistrationForm(forms.Form):
    phone = forms.CharField(max_length=16, required=False)
    password = forms.CharField(max_length=255, required=False)
    code = forms.CharField(max_length=6, required=False)

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(RegistrationForm, self).__init__(*args, **kwargs)

    def clean_phone(self):
        phone = self.data['phone']
        phone = CheckPhone.re_phone(phone)
        if len(phone)<9:
            raise forms.ValidationError(u'Номер телефона должен содержать 10 символов')
        return phone


    def _exists_code(self):
        try:
            Code.objects.get(phone=self.cleaned_data.get('phone'), code=self.cleaned_data.get('code'))
        except Code.DoesNotExist:
            raise forms.ValidationError(u'Неверный код')


    def clean(self):
        if self.request.POST.get('button') =='check_in':
            self._exists_code()
        else:
            self.clean_phone()
        super(RegistrationForm, self).clean()
        return self.cleaned_data



class LoginForm(forms.Form):
    phone = forms.CharField(max_length=16)
    password = forms.CharField(max_length=255)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        phone = CheckPhone.re_phone(phone)
        return phone



class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(max_length=255)
    new_password = forms.CharField(max_length=255)
    new_password_again = forms.CharField(max_length=255)

    def clean(self):
        new_password = self.data.get('new_password')
        new_password_again = self.data.get('new_password_again')
        if new_password != new_password_again:
            raise forms.ValidationError(u"Пароли должны совпадать. Попробуйте еще раз.")
        return self.cleaned_data

main/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime, timedelta


from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import  redirect
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.hashers import check_password
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.http import require_POST
from django.views.generic import ListView, FormView, DetailView, TemplateView
from django.core.urlresolvers import reverse
from django import forms

from dishes.models import DailyMenu
from main.forms import RegistrationForm, LoginForm, ChangePasswordForm
from .models import Client, Code
from basket.models import Basket, Order, OrderItem, Address
from .service import GetCurrentPoint, GetRouteId, VerificationCodeService, SmsCode


class WeeklyMenuListView(ListView):
    model = DailyMenu
    today = datetime.today()
    template_name = 'main/weekly_menu.html'

    def get_context_data(self, **kwargs):
        context = super(WeeklyMenuListView, self).get_context_data(**kwargs)
        if self.today.weekday() <= 6:
            context['start'] = self.today - timedelta(days=self.today.weekday())
            context['finish'] = context['start'] + timedelta(days=6)
        else:
            context['start'] = self.today-timedelta(days=self.today.weekday())+timedelta(days=7)
            context['finish'] = context['start']+timedelta(days=6)
        context['menues'] = DailyMenu.objects.filter(date__gte=context['start'], date__lte=context['finish']).order_by('date')
        return context


class HomeListView(TemplateView):

    template_name = 'main/home.html'

    def get_queryset(self):
        daily_menu = DailyMenu.objects.get(date=datetime.today())
        return daily_menu



class RegistrationFormView(FormView):
    template_name = 'main/home.html'
    form_class = RegistrationForm
    success_url = '/'

    def get_form_kwargs(self):
        kwargs = super(RegistrationFormView, self).get_form_kwargs()
        kwargs.update({
            'request': self.request
        })
        return kwargs

    def form_valid(self, form):

        phone = form.cleaned_data.get('phone')
        #Если нажата кнопта "отправить смс", для веденного номера генерируется рандомный код, который отправляется на sms.ru
        if self.request.POST.get('button') == 'send_sms':
            new_code = VerificationCodeService.regen_key(phone)
            #вызывается сервис для проверки ответа сервиса и вывода возможной ошибки
            res = SmsCode.send_sms(code=new_code, phone=phone)
            if res != 100:
                form.add_error('phone', forms.ValidationError(u'Вы ввели нерабочий номер телефона'))
                return super(RegistrationFormView, self).form_invalid(form)

        if self.request.POST.get('button') == 'check_in':
            try:
                Client.objects.get(phone=phone)
            except Client.DoesNotExist:
                new_user = User.objects.create_user(username=phone, password=form.cleaned_data.get('password'))
                Client.objects.create(phone=phone, user=new_user)
                login(self.request, new_user)
        return super(RegistrationFormView, self).form_valid(form)




class LoginFormView(FormView):
    template_name = 'main/home.html'
    form_class = LoginForm
    success_url = '/profile/'



    def form_valid(self, form):
        phone=form.cleaned_data.get('phone')
        try:
            Client.objects.get(phone=phone)
            user = authenticate(self.request, username=phone, password=form.cleaned_data.get('password'))
            if user:
                login(self.request, user)
                return super(LoginFormView, self).form_valid(form)
            else:
                form.add_error(None, forms.ValidationError(u'Неверный пароль'))
                return super(LoginFormView, self).form_invalid(form)
        except Client.DoesNotExist:
            return redirect ('home')


class LogoutView(View):

    def post(self, request):
        logout(request)
        return redirect('home')


class ChangePasswordFormView(FormView):
    template_name = 'main/profile.html'
    form_class = ChangePasswordForm
    success_url = '/'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ChangePasswordFormView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        if check_password(form.cleaned_data.get('current_password'), self.request.user.password):
            self.request.user.set_password(form.cleaned_data.get('new_password'))
            self.request.user.save()
        return super(ChangePasswordFormView, self).form_valid(form)




class BasketChangeQuantityView(View):

    @method_decorator(require_POST)
    def dispatch(self, request, *args, **kwargs):
        return super(BasketChangeQuantityView, self).dispatch(request, *args, **kwargs)

    def post(self, request):
        item_id = request.POST.get('item_id')
        basket = Basket.objects.get(id=request.basket.id)
        item = basket.items.get(id=item_id)
        if request.POST.get('action') == 'decrease':
            item.quantity = item.quantity - 1 if item.quantity > 0 else 0
        else:
            item.quantity = item.quantity + 1
        item.save()

        js_dict = {'quantity': item.quantity,'position': basket.positions, 'price': basket.sum_cost }
        if request.is_ajax():
            return JsonResponse (js_dict)

        else:
            return redirect('home')


class AddressTemplateView(View):


    @method_decorator(require_POST)
    def dispatch(self, request, *args, **kwargs):
        return super(AddressTemplateView, self).dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        basket = Basket.objects.get(id=request.basket.id)
        cur_address = Address.objects.create(
                address=request.POST.get('address'),
                longitude=request.POST.get('longitude'),
                latitude=request.POST.get('latitude'),
            )
        basket.address = cur_address
        basket.save()
        return HttpResponse(status=201)


class TimeDeliveryView(View):

    @method_decorator(require_POST)
    def dispatch(self, request, *args, **kwargs):
        return super(TimeDeliveryView, self).dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        try:
            minute = request.POST.get('minute')
            hour = request.POST.get('hour')
            basket = Basket.objects.get(id=request.basket.id)
            if hour and minute:
                basket.delivery_at = datetime.today().replace(hour=int(hour), minute=int(minute))
                basket.save()
                order = Order.objects.create(client=self.request.user.client, address=basket.address, delivery_at=basket.delivery_at)
                #Вызывается метод, который делает запрос на "http://cme.frfrdev.ru", для получения id маршрута курьера
                GetRouteId.get_route_id(order_id=order.id)
                return HttpResponseRedirect (reverse('order_detail', kwargs= {'order_id': order.id}))
            else:
                return  redirect('home')
        except ValueError:
            return redirect('home')



class OrderDetailView(DetailView):
    model = Order
    template_name = 'main/detail.html'
    pk_url_kwargs = 'order_id'
    query_pk_and_slug = True


    def get_object(self, queryset=None):
        return Order.objects.get(id=self.kwargs['order_id'])


    def get_context_data(self, **kwargs):
        order = Order.objects.get(id=self.kwargs['order_id'])
        context = super(OrderDetailView, self).get_context_data(**kwargs)
        basket_items = self.request.basket.items.exclude(quantity=0)

        if not basket_items:
            return context
        for item in basket_items:
            try:
                OrderItem.objects.get(order=order, dinner=item.dinner, quantity=item.quantity)
            except OrderItem.DoesNotExist:
                    OrderItem.objects.create(order=order, dinner=item.dinner, quantity=item.quantity)
        context['time_now'] = order.created_at+timedelta(hours=5)
        context['items'] = order.orderitem_set.all()



        return context

class GetCurrentCourierView(View):

    def get(self, request):
        order_id = request.GET.get('order_id')
        current_response = GetCurrentPoint.get_cur_point(order_id=order_id)
        return JsonResponse(current_response)


class ProfileView(ListView):

    template_name = 'main/profile.html'
    paginate_by = 10
    context_object_name = 'orders'

    def get_queryset(self):
        orders = Order.objects.filter(client=self.request.user.client).exclude(orderitem__quantity__isnull=True).order_by('-delivery_at')
        return orders

main/templates/main/detail.html
{% extends 'base.html' %}
{% block title %} Детали доставки {% endblock %}
{% block content %}
        <div class="detail">
          <div class="detail__inner">

              <div class="detail__title">Детали заказа № <span id="order_id">{{ order.id }}</span></div>
            <div class="detail__desc">
              <div class="detail__date">{{ order.delivery_at|date:"d.m.Y" }}</div>
                <div class="detail__time">{{ time_now|date:"H.i" }}</div>
                <div><span id="route_id" hidden="true">{{ order.courier_id }}</span></div>
            </div>

            <div class="detail__order">
                {% for order_item in items %}
              <div class="detail__item">

                <div class="weekly__item">
                    {% include 'include/menu_include.html' with dinner=order_item.dinner order_item=order_item %}

                </div>
              </div>

{% endfor %}
            </div>

            <div class="detail__order-info">
                <div class="detail__delivery">100</div>
              <div class="detail__itogo">{{ order.sum_cost }}</div>
            </div>
            <div class="detail__courier">Курьер уже в пути!<br>Ориентировочное время доставки <span class='detail__courier-time'>{{ order.delivery_at|date:'H:i' }}</span></div>
              <div id="YMapsID" style="width: 1000px; height: 1000px">
                  <script src="https://api-maps.yandex.ru/2.0/?load=package.standard&mode=debug&lang=ru-RU" type="text/javascript"></script>

              </div>



          </div>

        </div>



        {% endblock %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Ресторан доставки обедов  Kotletas{% endblock %}
{% block content %}
    <div class="hero">
        <div style="background-image:url('../static/img/design/main.png')" class="hero__image"></div>
        <div class="layout__inner">
            <div class="hero__cont">
                <div class="hero__text">доставка <span>обедов</span></div>
            </div>
            <div class="hero__bottom">
                <div class="hero__bottom-text">СМОТРИ МЕНЮ НА СЕГОДНЯ<span></span></div>
            </div>
        </div>
    </div>
    <div class="menu">
        <div class="layout__inner">
            <div class="menu__cont">
                {% for item in basket.items.all %}
                   {% include 'include/menu_include.html' with dinner=item.dinner item=item %}
                {% endfor %}

            </div>
        </div>
    </div>
    <div class="order">


        {% if not user.is_authenticated %}

             <div class="form main__form">
            <div class="form__title">ОФОРМИТЬ ЗАКАЗ</div>
            <div class="form__tab">
                <div data-tab="tab_1" class="form__tab-item active">ВХОД</div>
                <div data-tab="tab_2" class="form__tab-item">РЕГИСТРАЦИЯ</div>
            </div>
            <div data-tab="tab_1" class="form__item active">
                <form class="form__this" method="post" action="{% url 'login' %}">
                    {% csrf_token %}
                    <div class="form__line">
                        <div data-input="Номер телефона" class="input__cont input__phone">
                            <input id="id_phone" name="phone" class="input__this input__this-phone"/>
                        </div>
                    </div>
                    {%   if form.non_field_errors %}
                    <div class="form__line error">
                    {% else %}
                        <div class="form__line ">
                            {% endif %}
                        <div data-input="Пароль" class="input__cont">
                            <input type="password" name="password" class="input__this"/>
                        </div>
                    </div>
                    <div class="form__bottom">
                        <button class="button">ПРОДОЛЖИТЬ</button>
                    </div>
                </form>
            </div>
            <div data-tab="tab_2" class="form__item">
                <form class="form__this" method='post' action="{% url 'registration' %}">
                    {% csrf_token %}

                    {% if   form.phone.errors %}
                        <div class="form__line error">
                    {% else %}
                        <div class="form__line ">

                    {% endif %}
                        <div data-input="Номер телефона" class="input__cont input__phone">

                            <input id="id_phone" name="phone" class="input__this input__this-phone" />

                        </div>
                    </div>
                    <div class="form__line form__line-sms">
                        <button class="button__sms" name = 'button' value = 'send_sms'>Выслать SMS-код</button>

                           {% if form.non_field_errors %}
                               <div class="form__sms error">
                               <div class="form__sms-error">Неверный или пустой код</div>
                               {% else %}
                                   <div class="form__sms ">
                                       {% endif %}
                            <div class="form__sms-text">SMS-КОД:</div>
                            <div class="form__sms-right">
                                <input name='code' class="form__sms-input"/>


                            </div>
                        </div>
                    </div>
                    <div class="form__line">
                        <div data-input="Пароль" class="input__cont">
                            {{ form.password.errors }}
                            <input type="password" name='password' class="input__this"/>

                        </div>
                    </div>
                    <div class="form__bottom">
                        <button class="button" name = 'button' value = 'check_in'>РЕГИСТРАЦИЯ</button>

                    </div>
                </form>
            </div>
        </div>
 {% else %}

         <div class="form order__address" >
            <div class="form__title">ОФОРМИТЬ ЗАКАЗ</div>
            <div class="form__desc">АДРЕС ДОСТАВКИ</div>
            <form class="form__this form__address" method="post" action="{% url 'address' %}">
                {% csrf_token %}
              <div class="form__line">
                <div data-input="Ваш адрес " class="input__cont">
                  <input id ='address' required ='' name='address' type="text" class="input__this"/>
                </div>
              </div>
              <div class="form__more">Если все верно:</div>
              <div class="form__bottom">
                <button type="submit" class="button">ПРОДОЛЖИТЬ</button>
              </div>
            </form>
          </div>

          <div class="form order__time" style="display: none;">
            <div class="form__title">ОФОРМИТЬ ЗАКАЗ</div>
            <div class="form__desc">УКАЗАТЬ ВРЕМЯ ДОСТАВКИ</div>
            <form class="form__this" action="{% url 'time'%}" method="post" >
                {% csrf_token %}
              <div class="form__line form__line-time">

                <div class="form__time ">
                  <input placeholder="00" name='hour' id='hour' class="form__time-input"/>
                </div>
                <div class="form__time">
                  <input placeholder="00" name='minute' value="00" class="form__time-input"/>
                </div>
              </div>
              <div class="form__bottom">
                <button class="button">ПРОДОЛЖИТЬ</button>
              </div>
            </form>
          </div>


{% endif %}

    </div>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <!--[if lt IE 10]>
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery-ajaxtransport-xdomainrequest/1.0.1/jquery.xdomainrequest.min.js"></script>
    <![endif]-->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery.suggestions/17.2/js/jquery.suggestions.min.js"></script>
    <script type="text/javascript">
    $("#address").suggestions({
        token: "35a81698e41e890314ce60b92a0e77f9a9df8b9b",
        type: "ADDRESS",
        /* Вызывается, когда пользователь выбирает одну из подсказок */
        onSelect: function(suggestion) {

            basketData = {
                address: suggestion.data.source,
                longitude: suggestion.data.geo_lon,
                latitude: suggestion.data.geo_lat,
            };
            console.log(suggestion);

        }
    });
</script>




{% endblock %}

main/templates/main/profile.html
{% extends 'base.html' %}

{% block title %}Личный кабинет{% endblock %}

{% block content%}


 <div class="persona">
          <div class="layout__inner">
            <div class="persona__inner">
              <div class="persona__title">Личный кабинет</div>
              <div class="persona__cont">
                <div class="persona__left">
                  <div class="persona__history">
                    <div class="history">
                      <div class="history__title">ИСТОРИЯ ЗАКАЗОВ</div>
                      <div class="history__cont">
                        <div class="history__table">
                          <table class="paginated">
                            <thead>
                              <tr>
                                <th scope="col" style="width:30%">Дата</th>
                                <th scope="col" style="width:40%">Стоимость, р.</th>
                                <th scope="col" style="width:30%">Статус</th>
                              </tr>
                            </thead>
                            <tbody>
                            {% for order in orders %}
                              <tr data-href="/detail.html" class="clickable-row">
                                <td class="history__date">{{ order.delivery_at|date:'d.m.Y' }}</td>
                                <td>{{ order.sum_cost }}</td>
                                  {% if order.status %}
                                      <td data-status="end" class="history__status"></td>
                                    {% else %}
                                <td data-status="work" class="history__status"></td>
                                 {% endif %}
                              {% endfor %}
                              </tr>

                            </tbody>
                          </table>
                        </div>
                        <div class="pager">
                          <a class="page__control page__first">
                          </a>
                          <a class=" page__control page__prev">
                                        </a>
                          <a class=" page__control page__next">
                                        </a>
                          <a class=" page__control page__last">
                                        </a>
                          <div class="pager__box">

                              {% for page_number in paginator.page_range %}
                              <span class="page-number clickable active {% if page.number == page_number %}
                              active {% endif %}">
                          <a href="?page={{ page_number }}">{{ page_number }}</a></span>
                              {% endfor%}
                                        </div>
                                    </div>
                      </div>
                    </div>
                  </div>
                  <div class="persona__options">
                    <div class="options">
                      <div class="options__title">НАСТРОЙКИ</div>
                      <form class="options__form" method='post' action="{% url 'change_password' %}">
                          {% csrf_token %}
                        <div class="options__line">
                          <div data-input="Текущий пароль" class="input__cont">
                            <input type="password" name="current_password" class="input__this"/>
                          </div>
                        </div>
                        <div class="options__line">
                          <div data-input="Новый пароль" class="input__cont">
                            <input type="password" name='new_password' class="input__this"/>
                          </div>
                        </div>
                        <div class="options__line">
                          <div data-input="Повторить новый пароль" class="input__cont">
                            <input type="password" name= 'new_password_again' class="input__this"/>
                          </div>
                        </div>
                        <div class="options__bottom">
                          <button class="button" type="submit">СОХРАНИТЬ</button>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
                <div class="persona__right">
                  <div class="statham">
                    <div class="statham__item"><img src="/media/statham_01.png"/></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>


{% endblock %}

main/templates/main/weekly_menu.html
{% extends 'base.html' %}
{% block title %}Меню на неделю{% endblock %}
{% block content %}
    <div class="weekly">
        <div class="weekly__inner">
            <div class="weekly__title">МЕНЮ НА НЕДЕЛЮ</div>
            <div class="weekly__date">{{ start|date:"d.m.Y" }} - {{ finish|date:"d.m.Y" }}</div>
            <div class="weekly__cont">
                {% for menu in menues %}
                    <div data-day="{{ menu.date|date:'l' }}" class="weekly__line">
                        <div class="weekly__box">
                            {% for dinner in menu.dinners.all %}
                                <div class="weekly__item">
                                {% include 'include/menu_include.html' %}
                                </div>
                            {% endfor %}


                        </div>

                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}